### ISSUE TITLE
TRAL does not find “Phobos result file”

### ISSUE THREAD

**Issue by smoretti** [elkeschaper/tral#12]
Hi

we have a user problem report within Vital-IT queuing system about TRAL.
See https://bioinformatics.stackexchange.com/questions/4661/tral-does-not-find-phobos-result-file

Could you help him?

Best

> Dear Sir/Madam,
> 
> I would like to use 
> your Python module TRAL to annotate the tandem repeats of the C. elegans 
> genome. I got into some issues that I described here on Bioinformatics 
> Stackexchange:
> 
> https://bioinformatics.stackexchange.com/questions/4661/tral-does-not-find-phobos-result-file
> 
> Could you please help me resolve my problem?
> 
> Thanks.
> 
> Best wishes,
> 
> Cristian.

**Comment by sbliven** [comment]
I can reproduce the error described in the link. To summarize:

Running Phobos through TRAL on Macs isn't working.

Config file:
```
    [[repeat_detection]]
        AA = T-REKS
        DNA = Phobos
    [[repeat_detector_path]]
        PHOBOS = /path/phobos-mac-intel-64bit-start-from-command-line
```

Code:
```
import os
from tral.sequence import sequence
from tral.paths import PACKAGE_DIRECTORY
proteome_HIV = os.path.join(PACKAGE_DIRECTORY, "examples", "data", "HIV-1_388796.faa")
sequences_HIV = sequence.Sequence.create(file = proteome_HIV, input_format = 'fasta')
tandem_repeats = sequences_HIV[0].detect(denovo = True, detection = {"detectors": ["Phobos"]})
```

Error:
```
Did not find Phobos result file in /var/folders/b6/l31x0kx14k9_mc6n42wlvy2c0000gq/T/tmpch7c6p8s/001/PHOBOS/phobos.o
```

There's no indication of a phobos error, but I'm not that familiar with the expected behavior if no repeats were found. Maybe it's OK? The temp folder `/var/folders/b6/l31x0kx14k9_mc6n42wlvy2c0000gq/T/tmpch7c6p8s` doesn't exist for me after executing, but that might be normal cleanup.

**Comment by sbliven** [comment]
At first I thought it was because Phobos is DNA-only and the example fasta is protein. However, I'm still getting the log message on the HIV proteome (https://www.ebi.ac.uk/ena/data/view/K03455&display=fasta&download=fasta&filename=K03455.fasta)

**Comment by sbliven** [comment]
It appears the the Phobos interface has changed significantly since the TRAL adaptor was written. The exact bug referenced here has been fixed in the develop branch, but additional bugs with Phobos (#16) remain. The next version will update Phobos support to work with current versions.

I'm closing this issue, but we will continue to test Phobos and fix any bugs encountered.
